### Create a Restaurant
POST http://localhost:9194/api/v2/realm/restaurants

### Create a Seating
POST http://localhost:9194/api/v2/realm/seatings

### Create a Client
POST http://localhost:9194/api/v2/realm/clients

###
POST http://localhost:9194/api/v2/seating/booking
Content-Type: application/json

{
  "quantity": 2,
  "since": 2000000000,
  "until": 3000000000,
  "client": {
    "id": 1,
    "name": "1"
  },
  "seating": {
    "id": 1,
    "capacity": 2,
    "restaurant": {
      "id": 1
    }
  }
}
