# http://localhost:9194/swagger-ui.html

### Create a Restaurant
POST http://localhost:9194/api/v2/realm/restaurants
Authorization: Basic user pwd

### Create a Seating
POST http://localhost:9194/api/v2/realm/seatings
Authorization: Basic user pwd

### Get All Seatings
GET http://localhost:9194/api/v2/realm/seatings
Authorization: Basic user pwd

### Create a Client
POST http://localhost:9194/api/v2/realm/clients
Authorization: Basic user pwd

###
POST http://localhost:9194/api/v2/seating/booking
Authorization: Basic user pwd
Content-Type: application/json

{
  "id": 0,
  "quantity": 2,
  "since": 90000000000,
  "until": 90000720000,
  "client": {
    "id": 1
  },
  "seating": {
    "id": 1,
    "restaurant": {
      "id": 1
    }
  }
}

### Seating Cleaning in the Restaurant
POST http://localhost:9194/api/v2/seating/cleaning
Authorization: Basic user pwd
Content-Type: application/json

{
  "since": 90000000000,
  "seating": {
    "id": 1,
    "restaurant": {
      "id": 1
    }
  }
}
